# Development Docker Compose Override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: '3.8'

services:
  database:
    environment:
      POSTGRES_DB: agent_builder_dev
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@database:5432/agent_builder_dev
      ENVIRONMENT: development
      DEBUG: true
      LOG_LEVEL: DEBUG
      CORS_ORIGINS: http://localhost:3000,http://localhost:3001
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_db
      - uploads_data:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  # Remove nginx for development
  nginx:
    profiles: ["production"]